## 1

In [1]:
tosses = "251326344212463366565535614566523665561326345621443235213263461435421"

In [4]:
# 数字の出し方
int(tosses[0])

2

In [5]:
len(tosses)

69

In [6]:
prob_loaded = {"1": 1/12, "2": 1/12, "3": 1/12, "4": 1/12, "5":1/3, "6":1/3} 
prob_fair = {"1":1/6, "2":1/6, "3":1/6, "4":1/6, "5":1/6, "6":1/6}

In [11]:
import numpy as np
transition = np.array([[0.8, 0.3], [0.2, 0.7]])
transition[0,1]

0.29999999999999999

In [17]:
# 初期は半々の確率でloaded/ fair
import numpy as np

tosses = "251326344212463366565535614566523665561326345621443235213263461435421"
prob_loaded = {"1": 1/12, "2": 1/12, "3": 1/12, "4": 1/12, "5":1/3, "6":1/3} 
prob_fair = {"1":1/6, "2":1/6, "3":1/6, "4":1/6, "5":1/6, "6":1/6}

score_loaded = np.ones(len(tosses))
score_fair = np.ones(len(tosses))

score_loaded[0] = 0.5 * prob_loaded[tosses[0]]
score_fair[0] = 0.5 * prob_fair[tosses[0]]

for i in range(1,len(tosses)):
    score_loaded[i] = max(score_loaded[i-1] * transition[1,1], score_fair[i-1] * transition[1,0]) * prob_loaded[tosses[i]]
    score_fair[i] = max(score_loaded[i-1] * transition[0,1], score_fair[i-1] * transition[0,0]) * prob_fair[tosses[i]]

state_estimation = np.ones(len(tosses))
for n, j in enumerate(score_loaded - score_fair):
    if j < 0:
        state_estimation[n] = 0

print(state_estimation)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.  0.  0.  1.  1.
  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### 関数にしちゃう

In [18]:
import numpy as np

def vitervi(transition):
    tosses = "251326344212463366565535614566523665561326345621443235213263461435421"
    prob_loaded = {"1": 1/12, "2": 1/12, "3": 1/12, "4": 1/12, "5":1/3, "6":1/3} 
    prob_fair = {"1":1/6, "2":1/6, "3":1/6, "4":1/6, "5":1/6, "6":1/6}
    score_loaded = np.ones(len(tosses))
    score_fair = np.ones(len(tosses))
    score_loaded[0] = 0.5 * prob_loaded[tosses[0]]
    score_fair[0] = 0.5 * prob_fair[tosses[0]]
    
    for i in range(1,len(tosses)):
        score_loaded[i] = max(score_loaded[i-1] * transition[1,1], score_fair[i-1] * transition[1,0]) * prob_loaded[tosses[i]]
        score_fair[i] = max(score_loaded[i-1] * transition[0,1], score_fair[i-1] * transition[0,0]) * prob_fair[tosses[i]]

    state_estimation = np.ones(len(tosses))
    for n, j in enumerate(score_loaded - score_fair):
        if j < 0:
            state_estimation[n] = 0
            
    return(state_estimation)

In [19]:
transition1 = np.array([[0.8, 0.3], [0.2, 0.7]])
transition2 = np.array([[0.9, 0.15], [0.1, 0.85]])
transition3 = np.array([[0.95, 0.05], [0.6, 0.4]])
transition4 = np.array([[0.5, 0.5], [0.5, 0.5]])

In [20]:
vitervi(transition1)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [21]:
vitervi(transition2)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [22]:
vitervi(transition3)

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.])

In [23]:
vitervi(transition4)

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.])

## 2

In [2]:
# Gaussian Hermite quadrature
import numpy as np
from scipy.special import eval_hermite
from scipy.special import hermite
from scipy.special import h_roots
from scipy.special import he_roots
from scipy.stats import norm

In [26]:
# これで良いのでは
eval_hermite(2, 2)

14.000000000000004

In [36]:
hermite(2)

poly1d([ 4.,  0., -2.])

In [46]:
# こっちを使う
# 左側のarrayがsample pointsで、右側のarrayがweights
a = h_roots(2)

In [51]:
len(a[0])

2

In [7]:
a = h_roots(3)
a

(array([-1.22474487,  0.        ,  1.22474487]),
 array([ 0.29540898,  1.1816359 ,  0.29540898]))

In [8]:
a[0]

array([-1.22474487,  0.        ,  1.22474487])

In [3]:
np.sqrt(np.pi) * 2/3

1.1816359006036772

In [4]:
np.sqrt(np.pi)/6

0.2954089751509193

In [5]:
np.sqrt(6)/2

1.2247448713915889

In [45]:
norm.pdf(0)

0.3989422804014327

In [17]:
def GH(m):
    points = h_roots(m)[0]
    weights = h_roots(m)[1]
    return sum([weights[i] * np.exp(points[i]**2) * norm.pdf(points[i]) for i in range(len(points))])

In [18]:
GH(5)

0.99684628222456162

In [19]:
GH(10)

0.99998763906433263

In [20]:
GH(20)

0.99999999979803234

In [21]:
GH(30)

0.99999999999999634

In [5]:
def GH_weights(m):
    points = h_roots(m)[0]
    weights =  h_roots(m)[1]
    return [weights[i] * np.exp(points[i]**2) for i in range(len(points))]

In [6]:
GH_weights(5)

[1.1814886255359833,
 0.98658099675142807,
 0.94530872048294179,
 0.98658099675142807,
 1.1814886255359833]

In [7]:
GH_weights(10)

[1.0254516913657519,
 0.82066612640481784,
 0.74144193194356545,
 0.70329632310490586,
 0.6870818539512733,
 0.6870818539512733,
 0.70329632310490586,
 0.74144193194356545,
 0.82066612640481784,
 1.0254516913657519]

In [8]:
GH_weights(20)

[0.89859196145317,
 0.70433296117692357,
 0.62227869619138665,
 0.57526244285250083,
 0.54485174236452072,
 0.52408035094855054,
 0.50967902711745705,
 0.49992087133628998,
 0.4938433852720529,
 0.49092150066674595,
 0.49092150066674595,
 0.4938433852720529,
 0.49992087133628998,
 0.50967902711745705,
 0.52408035094855054,
 0.54485174236452072,
 0.57526244285250083,
 0.62227869619138665,
 0.70433296117692357,
 0.89859196145317]

In [9]:
GH_weights( 30)

[0.83424747101269592,
 0.64909798155433118,
 0.56940269194957616,
 0.52252568933130883,
 0.49105799583287552,
 0.4683748125647248,
 0.451321035991189,
 0.43817702265268194,
 0.42791806293273793,
 0.41989500373682354,
 0.41367936361113872,
 0.40898157500353133,
 0.40560512332568432,
 0.40341981692480389,
 0.40234606670190304,
 0.40234606670190304,
 0.40341981692480389,
 0.40560512332568432,
 0.40898157500353133,
 0.41367936361113872,
 0.41989500373682354,
 0.42791806293273793,
 0.43817702265268194,
 0.451321035991189,
 0.4683748125647248,
 0.49105799583287552,
 0.52252568933130883,
 0.56940269194957616,
 0.64909798155433118,
 0.83424747101269592]

## 3

jacobiはわからんクネ？

レポートには重みとかの計算も書こう

In [13]:
import numpy as np
from scipy.special import p_roots
from scipy.special import u_roots
from scipy.special import t_roots

In [2]:
p_roots(3)

(array([-0.77459667,  0.        ,  0.77459667]),
 array([ 0.55555556,  0.88888889,  0.55555556]))

In [4]:
np.sqrt(3/5)

0.7745966692414834

In [5]:
def f(x):
    return (x**9) / np.sqrt(x**2 + 1)

In [11]:
def GL(m, a, b):
    points = p_roots(m)[0]
    weights = p_roots(m)[1]
    return (b-a)*sum([weights[i]*f((b-a)*points[i]/2 + (b+a)/2)  for i in range(len(points))])/2

In [12]:
GL(5, -2, 1)

-49.506283813990549

In [15]:
def Cheby1(m, a, b):
    points = t_roots(m)[0]
    weights = t_roots(m)[1]
    return (b-a)*sum([weights[i]*np.sqrt(1-(points[i])**2) * f((b-a)*points[i]/2 + (b+a)/2)  for i in range(len(points))])/2

In [16]:
Cheby1(5, -2, 1)

-57.161045874594777

In [17]:
def Cheby2(m, a, b):
    points = u_roots(m)[0]
    weights = u_roots(m)[1]
    return (b-a)*sum([(weights[i]/np.sqrt(1-(points[i])**2)) * f((b-a)*points[i]/2 + (b+a)/2)  for i in range(len(points))])/2

In [18]:
Cheby2(5, -2, 1)

-40.789633611622008

In [20]:
GL(10, -2, 1)

-49.493963006199031

In [21]:
Cheby1(10, -2, 1)

-50.987455239343021

In [22]:
Cheby2(10, -2, 1)

-47.101342989695162

## 4
(p_a, p_b, p_o)

とりあえず10回やる

In [17]:
import numpy as np
from scipy.stats import binom

n = 25

iteration = 10
values = np.ones((iteration, 3))
initial_value = [1/3, 1/3, 1/3]
values[0, :] = initial_value

for ite in range(1, iteration):
    q_a = (2*values[ite-1, 2]) / (2*values[ite-1, 2] + values[ite-1, 0])
    q_b = (2*values[ite-1, 2]) / (2*values[ite-1, 2] + values[ite-1, 1])
    under = sum([binom.pmf(i, n, q_a) * binom.pmf(j, n, q_b) * (3*n - i) for i in range(n+1) for j in range(n+1)])
    upper = sum([binom.pmf(i, n, q_a) * binom.pmf(j, n, q_b) * (2*n + i + j) for i in range(n+1) for j in range(n+1)])
    values[ite, 0] = 1/(2+(upper/under))
    values[ite, 1] = 1/(2+(upper/under))
    values[ite, 2] = 1 - 2*values[ite, 0]

In [18]:
values

array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.29166667,  0.29166667,  0.41666667],
       [ 0.28240741,  0.28240741,  0.43518519],
       [ 0.28062249,  0.28062249,  0.43875502],
       [ 0.28028825,  0.28028825,  0.43942349],
       [ 0.28022601,  0.28022601,  0.43954798],
       [ 0.28021443,  0.28021443,  0.43957114],
       [ 0.28021227,  0.28021227,  0.43957545],
       [ 0.28021187,  0.28021187,  0.43957625],
       [ 0.2802118 ,  0.2802118 ,  0.4395764 ]])

## 5

In [2]:
# data generate
import numpy as np

I = 100
J = 2
beta_0 = -1
beta_1 = 1
sigma_u = 0.5
sigma_eps = 1

np.random.seed(12345)

value_x = np.random.normal(0, 1, (I, J))
u = np.random.normal(0, sigma_u, I)
value_u = np.ones((I, J))
value_u[:, 0] = u
value_u[:, 1] = u
value_eps = np.random.normal(0, sigma_eps, (I, J))
value_y = beta_0 + beta_1 * value_x + value_u + value_eps

In [9]:
# EM algorithm
# para = (beta_0, beta_1, sigma_eps, sigma_u)
# sigma is variance

iteration = 50

XY = sum(sum(value_y * value_x))
X = sum(sum(value_x))
Y = sum(sum(value_y))
X_2 = sum(sum(value_x * value_x))

def xE(E_t):
    return sum(sum(value_x * np.array([E_t, E_t]).T))

def eps_right(E_t, beta0, beta1):
    return (sum(sum((value_y - beta0-beta1*value_x)**2)) + J * sum(E_t**2) - 2*sum(sum((value_y - beta0 - beta1*value_x) * np.array([E_t, E_t]).T)))/(2*I*J)

initial = [0, 0, 5, 5]
E_t = np.ones(I)
estimation = np.ones((iteration, 4))
estimation[0, :] = initial

for ite in range(1,iteration):
    u = estimation[ite-1, 3]
    eps = estimation[ite-1, 2]
    beta0 = estimation[ite-1, 0]
    beta1 = estimation[ite-1, 1]
    for i in range(I):
        E_t[i] = u*sum([value_y[i, j] - beta0 - beta1*value_x[i, j] for j in range(J)]) / (J*u + eps)
    V_t = eps*u/(J*u + eps)
    estimation[ite, 1] = (I*J *XY - Y*X - J * (I*xE(E_t) - sum(E_t)*X))/(I*J*X_2 - X**2)
    estimation[ite, 0] = (Y-beta1*X - J* sum(E_t))/(I*J)
    estimation[ite, 2] = V_t/2 + eps_right(E_t, estimation[ite-1, 0], estimation[ite-1, 1])
    estimation[ite, 3] = V_t/2 + J*sum(E_t**2)/(2*I*J)

In [10]:
estimation

array([[  0.00000000e+00,   0.00000000e+00,   5.00000000e+00,
          5.00000000e+00],
       [ -3.41030963e-01,   6.98219245e-01,   1.50101815e+00,
          1.42223358e+00],
       [ -5.76391499e-01,   9.49381415e-01,   6.23593560e-01,
          5.57088371e-01],
       [ -7.36353594e-01,   1.03860065e+00,   4.35095701e-01,
          3.25011703e-01],
       [ -8.50916354e-01,   1.07206154e+00,   4.04722862e-01,
          2.37583802e-01],
       [ -9.29626953e-01,   1.08585345e+00,   4.12725430e-01,
          1.86534201e-01],
       [ -9.78157044e-01,   1.09278110e+00,   4.33291752e-01,
          1.48436674e-01],
       [ -1.00418441e+00,   1.09737231e+00,   4.60856699e-01,
          1.16382075e-01],
       [ -1.01602994e+00,   1.10114912e+00,   4.94222154e-01,
          8.78312910e-02],
       [ -1.02044115e+00,   1.10455068e+00,   5.32796589e-01,
          6.24029510e-02],
       [ -1.02170875e+00,   1.10758690e+00,   5.74595946e-01,
          4.09911046e-02],
       [ -1.02196599e

In [11]:
# change the last variance into standard deviation
estimation[:, 2] = np.sqrt(estimation[:, 2])
estimation[:, 3] = np.sqrt(estimation[:, 3])
estimation

array([[  0.00000000e+00,   0.00000000e+00,   2.23606798e+00,
          2.23606798e+00],
       [ -3.41030963e-01,   6.98219245e-01,   1.22516046e+00,
          1.19257435e+00],
       [ -5.76391499e-01,   9.49381415e-01,   7.89679404e-01,
          7.46383528e-01],
       [ -7.36353594e-01,   1.03860065e+00,   6.59617844e-01,
          5.70097977e-01],
       [ -8.50916354e-01,   1.07206154e+00,   6.36178326e-01,
          4.87425689e-01],
       [ -9.29626953e-01,   1.08585345e+00,   6.42437102e-01,
          4.31896054e-01],
       [ -9.78157044e-01,   1.09278110e+00,   6.58249004e-01,
          3.85274804e-01],
       [ -1.00418441e+00,   1.09737231e+00,   6.78864272e-01,
          3.41148172e-01],
       [ -1.01602994e+00,   1.10114912e+00,   7.03009355e-01,
          2.96363444e-01],
       [ -1.02044115e+00,   1.10455068e+00,   7.29929167e-01,
          2.49805827e-01],
       [ -1.02170875e+00,   1.10758690e+00,   7.58021072e-01,
          2.02462601e-01],
       [ -1.02196599e